config/routes.rb
Rails.application.routes.draw do
  resources :laboratories
  resources :departments
  resources :colleges
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/college.rb
class College < ApplicationRecord
    has_many :departments, -> { includes :laboratories }, dependent: :delete_all
end

app/models/department.rb
class Department < ApplicationRecord
    belongs_to :college
    has_many :laboratories, dependent: :delete_all
end

app/models/laboratory.rb
class Laboratory < ApplicationRecord
    belongs_to :department
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/colleges_controller.rb
class CollegesController < ApplicationController
  before_action :set_college, only: %i[ show edit update destroy ]

  # GET /colleges or /colleges.json
  def index
    @colleges = College.all
  end

  # GET /colleges/1 or /colleges/1.json
  def show
  	@colleges = College.find_by(params[:id])
  end

  # GET /colleges/new
  def new
    @college = College.new
  end

  # GET /colleges/1/edit
  def edit
  end

  # POST /colleges or /colleges.json
  def create
    @college = College.new(college_params)

    respond_to do |format|
      if @college.save
        format.html { redirect_to college_url(@college), notice: "College was successfully created." }
        format.json { render :show, status: :created, location: @college }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @college.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /colleges/1 or /colleges/1.json
  def update
    respond_to do |format|
      if @college.update(college_params)
        format.html { redirect_to college_url(@college), notice: "College was successfully updated." }
        format.json { render :show, status: :ok, location: @college }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @college.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /colleges/1 or /colleges/1.json
  def destroy
    @college.destroy!

    respond_to do |format|
      format.html { redirect_to colleges_url, notice: "College was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_college
      @college = College.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def college_params
      params.require(:college).permit(:name, :location)
    end
end

app/controllers/departments_controller.rb
class DepartmentsController < ApplicationController
  before_action :set_department, only: %i[ show edit update destroy ]

  # GET /departments or /departments.json
  def index
    @departments = Department.all
  end

  # GET /departments/1 or /departments/1.json
  def show
  end

  # GET /departments/new
  def new
    @department = Department.new
  end

  # GET /departments/1/edit
  def edit
  end

  # POST /departments or /departments.json
  def create
    @department = Department.new(department_params)

    respond_to do |format|
      if @department.save
        format.html { redirect_to department_url(@department), notice: "Department was successfully created." }
        format.json { render :show, status: :created, location: @department }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @department.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /departments/1 or /departments/1.json
  def update
    respond_to do |format|
      if @department.update(department_params)
        format.html { redirect_to department_url(@department), notice: "Department was successfully updated." }
        format.json { render :show, status: :ok, location: @department }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @department.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /departments/1 or /departments/1.json
  def destroy
    @department.destroy!

    respond_to do |format|
      format.html { redirect_to departments_url, notice: "Department was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_department
      @department = Department.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def department_params
      params.require(:department).permit(:name, :location)
    end
end

app/controllers/laboratories_controller.rb
class LaboratoriesController < ApplicationController
  before_action :set_laboratory, only: %i[ show edit update destroy ]

  # GET /laboratories or /laboratories.json
  def index
    @laboratories = Laboratory.all
  end

  # GET /laboratories/1 or /laboratories/1.json
  def show
  end

  # GET /laboratories/new
  def new
    @laboratory = Laboratory.new
  end

  # GET /laboratories/1/edit
  def edit
  end

  # POST /laboratories or /laboratories.json
  def create
    @laboratory = Laboratory.new(laboratory_params)

    respond_to do |format|
      if @laboratory.save
        format.html { redirect_to laboratory_url(@laboratory), notice: "Laboratory was successfully created." }
        format.json { render :show, status: :created, location: @laboratory }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @laboratory.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /laboratories/1 or /laboratories/1.json
  def update
    respond_to do |format|
      if @laboratory.update(laboratory_params)
        format.html { redirect_to laboratory_url(@laboratory), notice: "Laboratory was successfully updated." }
        format.json { render :show, status: :ok, location: @laboratory }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @laboratory.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /laboratories/1 or /laboratories/1.json
  def destroy
    @laboratory.destroy!

    respond_to do |format|
      format.html { redirect_to laboratories_url, notice: "Laboratory was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_laboratory
      @laboratory = Laboratory.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def laboratory_params
      params.require(:laboratory).permit(:name, :location)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/colleges_helper.rb
module CollegesHelper
end

app/helpers/departments_helper.rb
module DepartmentsHelper
end

app/helpers/laboratories_helper.rb
module LaboratoriesHelper
end

app/views/colleges/_college.html.erb
<div id="<%= dom_id college %>">
  <p>
    <strong>Name:</strong>
    <%= college.name %>
  </p>

  <p>
    <strong>Location:</strong>
    <%= college.location %>
  </p>

</div>

app/views/colleges/_form.html.erb
<%= form_with(model: college) do |form| %>
  <% if college.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(college.errors.count, "error") %> prohibited this college from being saved:</h2>

      <ul>
        <% college.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :location, style: "display: block" %>
    <%= form.text_field :location %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/colleges/edit.html.erb
<h1>Editing college</h1>

<%= render "form", college: @college %>

<br>

<div>
  <%= link_to "Show this college", @college %> |
  <%= link_to "Back to colleges", colleges_path %>
</div>

app/views/colleges/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Colleges</h1>

<div id="colleges">
  <% @colleges.each do |college| %>
    <%= render college %>
    <p>
      <%= link_to "Show this college", college %>
    </p>
  <% end %>
</div>

<%= link_to "New college", new_college_path %>

app/views/colleges/new.html.erb
<h1>New college</h1>

<%= render "form", college: @college %>

<br>

<div>
  <%= link_to "Back to colleges", colleges_path %>
</div>

app/views/colleges/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @college %>

<h4> Departments and Respective Laboratories:</h4>

<table style="width:50%">

  <tbody>
    <%@college.each do |department|%>
      
     <tr> <td><strong> Department of <%=department.name%></strong></td></tr>
      <tr> <td><strong>Location: <%=department.location%><strong></td> </tr>

      <tr>
          <td><strong>Laboratories:<br></strong></td>
     
      </tr>
      <%department.laboratories.each do |laboratory|%>
        <tr>
          <td><strong><%= laboratory.name%></strong> -<%= laboratory.location%><br></td>
          

        </tr>
        <% end %>


  </tbody>

  
 

  <% end %>

</table>

<div>
  <%= link_to "Edit this college", edit_college_path(@college) %> |
  <%= link_to "Back to colleges", colleges_path %>

  <%= button_to "Destroy this college", @college, method: :delete %>
</div>

app/views/departments/_department.html.erb
<div id="<%= dom_id department %>">
  <p>
    <strong>Name:</strong>
    <%= department.name %>
  </p>

  <p>
    <strong>Location:</strong>
    <%= department.location %>
  </p>

  <p>
    <strong>College:</strong>
    <%= department.college_id %>
  </p>

</div>

app/views/departments/_form.html.erb
<%= form_with(model: department) do |form| %>
  <% if department.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(department.errors.count, "error") %> prohibited this department from being saved:</h2>

      <ul>
        <% department.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :location, style: "display: block" %>
    <%= form.text_field :location %>
  </div>

  <div class="field">
    <%= form.label :college_id %>
    <%= collection_select(:department, :college_id, College.all,:id, :name) %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/departments/edit.html.erb
<h1>Editing department</h1>

<%= render "form", department: @department %>

<br>

<div>
  <%= link_to "Show this department", @department %> |
  <%= link_to "Back to departments", departments_path %>
</div>

app/views/departments/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Departments</h1>

<div id="departments">
  <% @departments.each do |department| %>
    <%= render department %>
    <p>
      <%= link_to "Show this department", department %>
    </p>
  <% end %>
</div>

<%= link_to "New department", new_department_path %>

app/views/departments/new.html.erb
<h1>New department</h1>

<%= render "form", department: @department %>

<br>

<div>
  <%= link_to "Back to departments", departments_path %>
</div>

app/views/departments/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @department %>

<h2>List of Laboratories: </h2>

<table style="width:50%">


  <thead>
    <tr>
      <td><strong>Name</strong></td>
      <td><strong>Location</strong></td>
    </tr>
  </thead>
  <tbody style="width:100%">
    <%@department.laboratories.each do |laboratory|%>
      <tr>
        <td><%= laboratory.name%></td>
        <td><%= laboratory.location%></td>
      </tr>
    <% end %>
  </tbody>
</table>

<div>
  <%= link_to "Edit this department", edit_department_path(@department) %> |
  <%= link_to "Back to departments", departments_path %>

  <%= button_to "Destroy this department", @department, method: :delete %>
</div>

app/views/laboratories/_form.html.erb
<%= form_with(model: laboratory) do |form| %>
  <% if laboratory.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(laboratory.errors.count, "error") %> prohibited this laboratory from being saved:</h2>

      <ul>
        <% laboratory.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :location, style: "display: block" %>
    <%= form.text_field :location %>
  </div>

  <div class="field">
    <%= form.label :department_id %>
    <%= collection_select(:laboratory,:department_id,Department.all,:id,:name) %>
  </div>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/laboratories/_laboratory.html.erb
<div id="<%= dom_id laboratory %>">
  <p>
    <strong>Name:</strong>
    <%= laboratory.name %>
  </p>

  <p>
    <strong>Location:</strong>
    <%= laboratory.location %>
  </p>

  <p>
    <strong>Department:</strong>
    <%= laboratory.department_id %>
  </p>

</div>

app/views/laboratories/edit.html.erb
<h1>Editing laboratory</h1>

<%= render "form", laboratory: @laboratory %>

<br>

<div>
  <%= link_to "Show this laboratory", @laboratory %> |
  <%= link_to "Back to laboratories", laboratories_path %>
</div>

app/views/laboratories/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Laboratories</h1>

<div id="laboratories">
  <% @laboratories.each do |laboratory| %>
    <%= render laboratory %>
    <p>
      <%= link_to "Show this laboratory", laboratory %>
    </p>
  <% end %>
</div>

<%= link_to "New laboratory", new_laboratory_path %>

app/views/laboratories/new.html.erb
<h1>New laboratory</h1>

<%= render "form", laboratory: @laboratory %>

<br>

<div>
  <%= link_to "Back to laboratories", laboratories_path %>
</div>

app/views/laboratories/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @laboratory %>

<div>
  <%= link_to "Edit this laboratory", edit_laboratory_path(@laboratory) %> |
  <%= link_to "Back to laboratories", laboratories_path %>

  <%= button_to "Destroy this laboratory", @laboratory, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CollegeDepLabApplication</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>